# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '86928c66-da3e-414c-bb57-01896080aafa' # ACR service connection ID
  imageRepository: 'venu'                  # Image name
  containerRegistry: 'acrreg.azurecr.io'   # ACR login server
  dockerfilePath: 'Dockerfile'              # Path to Dockerfile (adjust if in a subfolder)
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: devops   # your self-hosted pool
    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and push an image to ACR
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

